/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 * \login frame 
 *
 * 
 */
package jcodeguard;

import java.awt.event.WindowEvent;
import jcodeguard.alpha.UsermasterBean;
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.WindowListener;
import jcodeguard.alpha.DBOperations;

/**
 *
 *  
 */
public class MainFrame extends javax.swing.JFrame implements WindowListener {

    UsermasterBean objUsermasterBean;
    static Container container;
    static int userId;
    static int userActivityID;

    /** Creates new form MainFrame */
    public MainFrame() {
        //initComponents();
        //setVisible(true);
    }

    public MainFrame(UsermasterBean objUsermasterBean, int userActivityID) {
        initComponents();
        this.objUsermasterBean = objUsermasterBean;
        this.userActivityID = userActivityID;
        userId=objUsermasterBean.getUserId();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setResizable(false);
        container = getContentPane();
        addWindowListener(this);
        if(objUsermasterBean.getUserType().equalsIgnoreCase("employee")){
            mbMainFrame.remove(mnuUserMaintenance);
            mbMainFrame.remove(mnuReports);
        }


        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbMainFrame = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mnuProfile = new javax.swing.JMenu();
        miProfileAccountDetail = new javax.swing.JMenuItem();
        miProfilePersonalDetail = new javax.swing.JMenuItem();
        mnuUserMaintenance = new javax.swing.JMenu();
        miUserAccountDetail = new javax.swing.JMenuItem();
        miUserPersonalDetail = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuOpenIDE = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        miUserAccountReport = new javax.swing.JMenuItem();
        miUserPersonalReport = new javax.swing.JMenuItem();
        miUserActivityReport = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mnuSavedProgram = new javax.swing.JMenuItem();
        mnuAccessedProgram = new javax.swing.JMenuItem();
        mnuUpdateProgram = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(miLogout);

        mbMainFrame.add(jMenu1);

        mnuProfile.setText("Profile");

        miProfileAccountDetail.setText("Profile Account Detail");
        miProfileAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfileAccountDetailActionPerformed(evt);
            }
        });
        mnuProfile.add(miProfileAccountDetail);

        miProfilePersonalDetail.setText("Profile Personal Detail");
        miProfilePersonalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfilePersonalDetailActionPerformed(evt);
            }
        });
        mnuProfile.add(miProfilePersonalDetail);

        mbMainFrame.add(mnuProfile);

        mnuUserMaintenance.setText("User Maintenance");

        miUserAccountDetail.setText("User Account Detail");
        miUserAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserAccountDetailActionPerformed(evt);
            }
        });
        mnuUserMaintenance.add(miUserAccountDetail);

        miUserPersonalDetail.setText("User Personal Detail");
        miUserPersonalDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserPersonalDetailActionPerformed(evt);
            }
        });
        mnuUserMaintenance.add(miUserPersonalDetail);

        mbMainFrame.add(mnuUserMaintenance);

        jMenu2.setText("Java IDE");

        mnuOpenIDE.setText("Open");
        mnuOpenIDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpenIDEActionPerformed(evt);
            }
        });
        jMenu2.add(mnuOpenIDE);

        mbMainFrame.add(jMenu2);

        mnuReports.setText("Reports");

        miUserAccountReport.setText("User Account Report");
        miUserAccountReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserAccountReportActionPerformed(evt);
            }
        });
        mnuReports.add(miUserAccountReport);

        miUserPersonalReport.setText("User Personal Report");
        miUserPersonalReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserPersonalReportActionPerformed(evt);
            }
        });
        mnuReports.add(miUserPersonalReport);

        miUserActivityReport.setText("User Activity Report");
        miUserActivityReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserActivityReportActionPerformed(evt);
            }
        });
        mnuReports.add(miUserActivityReport);

        jMenu7.setText("Program Report");

        mnuSavedProgram.setText("Saved Program");
        mnuSavedProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSavedProgramActionPerformed(evt);
            }
        });
        jMenu7.add(mnuSavedProgram);

        mnuAccessedProgram.setText("Accessed Program");
        mnuAccessedProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAccessedProgramActionPerformed(evt);
            }
        });
        jMenu7.add(mnuAccessedProgram);

        mnuUpdateProgram.setText("Updated Program");
        mnuUpdateProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUpdateProgramActionPerformed(evt);
            }
        });
        jMenu7.add(mnuUpdateProgram);

        mnuReports.add(jMenu7);

        mbMainFrame.add(mnuReports);

        setJMenuBar(mbMainFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUserAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserAccountDetailActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        UserAccountDetail objUserAccountDetail = new UserAccountDetail();
        objUserAccountDetail.setBounds(250, 100, 460, 420);
        container.setVisible(false);
        container.add(objUserAccountDetail);
        container.setVisible(true);
}//GEN-LAST:event_miUserAccountDetailActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        logout();
        
}//GEN-LAST:event_miLogoutActionPerformed

    private void miUserAccountReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserAccountReportActionPerformed
        // TODO add your handling code here:
        new UserAccountReport();
}//GEN-LAST:event_miUserAccountReportActionPerformed

    private void miUserPersonalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserPersonalDetailActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        UserPersonalDetail objUserPersonalDetail = new UserPersonalDetail();
        objUserPersonalDetail.setBounds(250, 100, 460, 450);
        container.setVisible(false);
        container.add(objUserPersonalDetail);
        container.setVisible(true);
    }//GEN-LAST:event_miUserPersonalDetailActionPerformed

    private void miProfileAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfileAccountDetailActionPerformed
        // TODO add your handling code here:
         container.removeAll();
        ProfileAccountDetail objUserAccountDetail = new ProfileAccountDetail();
        objUserAccountDetail.setBounds(250, 100, 460, 315);
        container.setVisible(false);
        container.add(objUserAccountDetail);
        container.setVisible(true);
    }//GEN-LAST:event_miProfileAccountDetailActionPerformed

    private void miProfilePersonalDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfilePersonalDetailActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        ProfilePersonalDetail objUserPersonalDetail = new ProfilePersonalDetail();
        objUserPersonalDetail.setBounds(250, 100, 460, 400);
        container.setVisible(false);
        container.add(objUserPersonalDetail);
        container.setVisible(true);
    }//GEN-LAST:event_miProfilePersonalDetailActionPerformed

    private void miUserPersonalReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserPersonalReportActionPerformed
        // TODO add your handling code here:
        new UserPersonalReport();
    }//GEN-LAST:event_miUserPersonalReportActionPerformed

    private void miUserActivityReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserActivityReportActionPerformed
        // TODO add your handling code here:
        new UserActivityReport();
    }//GEN-LAST:event_miUserActivityReportActionPerformed

    private void mnuOpenIDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpenIDEActionPerformed
   new IDE(userId);
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuOpenIDEActionPerformed

    private void mnuSavedProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSavedProgramActionPerformed
        // TODO add your handling code here:
        new SavedProgramsReport();
}//GEN-LAST:event_mnuSavedProgramActionPerformed

    private void mnuAccessedProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAccessedProgramActionPerformed
        // TODO add your handling code here:
        new ProgramsAccessedReport();
}//GEN-LAST:event_mnuAccessedProgramActionPerformed

    private void mnuUpdateProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUpdateProgramActionPerformed
        // TODO add your handling code here:
        new ProgramUpdateReport();
}//GEN-LAST:event_mnuUpdateProgramActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    void logout() {
        DBOperations objDB = new DBOperations();
        objDB.updateUserActivity(userActivityID);
  dispose();      
        new LoginFrame().setVisible(true);
//System.exit(0);
    }

    public void windowOpened(WindowEvent e) {
    }

    public void windowClosing(WindowEvent e) {
        logout();
    }

    public void windowClosed(WindowEvent e) {
    }

    public void windowIconified(WindowEvent e) {
    }

    public void windowDeiconified(WindowEvent e) {
    }

    public void windowActivated(WindowEvent e) {
    }

    public void windowDeactivated(WindowEvent e) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar mbMainFrame;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miProfileAccountDetail;
    private javax.swing.JMenuItem miProfilePersonalDetail;
    private javax.swing.JMenuItem miUserAccountDetail;
    private javax.swing.JMenuItem miUserAccountReport;
    private javax.swing.JMenuItem miUserActivityReport;
    private javax.swing.JMenuItem miUserPersonalDetail;
    private javax.swing.JMenuItem miUserPersonalReport;
    private javax.swing.JMenuItem mnuAccessedProgram;
    private javax.swing.JMenuItem mnuOpenIDE;
    private javax.swing.JMenu mnuProfile;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenuItem mnuSavedProgram;
    private javax.swing.JMenuItem mnuUpdateProgram;
    private javax.swing.JMenu mnuUserMaintenance;
    // End of variables declaration//GEN-END:variables
}
