/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgramsAccessedReport.java
 *
 
 */

package jcodeguard;

import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JTable;
import jcodeguard.alpha.DBOperations;
import jcodeguard.alpha.ProgramAccessMasterBean;
import jcodeguard.report.JasperReportGenerator;


/**
 *
 *  
 */
public class ProgramsAccessedReport extends javax.swing.JFrame {

    /** Creates new form ProgramsAccessedReport */

    ArrayList alstAccessedPrograms;
    ArrayList alstUsernameList;
    DBOperations objDB;
    public ProgramsAccessedReport() {
        initComponents();
        setVisible(true);
         
           setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            setSize(Toolkit.getDefaultToolkit().getScreenSize());
             objDB = new DBOperations();

        alstUsernameList = objDB.getUsernameList();
        if (alstUsernameList.size() > 0) {
            for (int i = 0; i < alstUsernameList.size(); i++) {
                ddlUsername.addItem(alstUsernameList.get(i));
            }
        }

        alstAccessedPrograms = objDB.getAcessedProgramReportList();
        generateTable();
    }
    void generateTable() {
        Object data[][] = new String[alstAccessedPrograms.size()][6];
        for (int i = 0; i < alstAccessedPrograms.size(); i++) {
            ProgramAccessMasterBean objBean = (ProgramAccessMasterBean) alstAccessedPrograms.get(i);


            data[i][0] = String.valueOf(objBean.getProgram_ID());
            data[i][1] = String.valueOf(objBean.getUser_ID());
            data[i][2] = String.valueOf(objBean.getViewer_User_ID());
            data[i][3] = objBean.getProgram_Name();
            data[i][4] = objBean.getCreate_Date();
            data[i][5] = objBean.getAccess_Date();

        }
        String header[] = {"Program ID", "Owner User ID", "Viewer User ID" ,"Program Name", "Create Date", "Access Date"};
        tblProgramAccessed = new JTable(data, header);
        jScrollPane1.setViewportView(tblProgramAccessed);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ddlUsername = new javax.swing.JComboBox();
        btnList = new javax.swing.JButton();
        btnListAll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProgramAccessed = new javax.swing.JTable();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        miPrint2 = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Owner Username");

        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnListAll.setText("List All");
        btnListAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18));
        jLabel1.setText("Programs Accessed Report");

        tblProgramAccessed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Program ID", "Owner User ID", "Viewer User ID", "Program Name", "CreateDate", "Access Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProgramAccessed);

        jMenu3.setText("File");

        miPrint2.setText("Print");
        miPrint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrint2ActionPerformed(evt);
            }
        });
        jMenu3.add(miPrint2);

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu3.add(miExit);

        jMenuBar3.add(jMenu3);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ddlUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnListAll, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(266, 266, 266))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnList)
                    .addComponent(btnListAll)
                    .addComponent(jLabel2)
                    .addComponent(ddlUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        alstAccessedPrograms = objDB.getAcessedProgramReportListByUsername((String)ddlUsername.getSelectedItem());
        generateTable();
    }//GEN-LAST:event_btnListActionPerformed

    private void btnListAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllActionPerformed
        // TODO add your handling code here:
        alstAccessedPrograms=objDB.getAcessedProgramReportList();
        generateTable();
    }//GEN-LAST:event_btnListAllActionPerformed

    private void miPrint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrint2ActionPerformed
        // TODO add your handling code here:
        String path = getClass().getResource("../jcodeguard/report/ProgramsAccessedReport.jrxml").getPath();
        JasperReportGenerator jrg=new JasperReportGenerator(path);
}//GEN-LAST:event_miPrint2ActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_miExitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramsAccessedReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnListAll;
    private javax.swing.JComboBox ddlUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miPrint2;
    private javax.swing.JTable tblProgramAccessed;
    // End of variables declaration//GEN-END:variables

}
