/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgramUpdateReport.java
 *

 */
package jcodeguard;

import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JTable;
import jcodeguard.alpha.DBOperations;
import jcodeguard.alpha.ProgramUpdateMasterBean;
import jcodeguard.report.JasperReportGenerator;


/**
 *
 *  
 */
public class ProgramUpdateReport extends javax.swing.JFrame {

    /** Creates new form ProgramUpdateReport */
    ArrayList alstUpdatedPrograms;
    ArrayList alstUsernameList;
    DBOperations objDB;

    public ProgramUpdateReport() {
        initComponents();
        setVisible(true);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        objDB = new DBOperations();

        alstUsernameList = objDB.getUsernameList();
        if (alstUsernameList.size() > 0) {
            for (int i = 0; i < alstUsernameList.size(); i++) {
                ddlUsername.addItem(alstUsernameList.get(i));
            }
        }

        alstUpdatedPrograms = objDB.getUpdatedProgramReportList();
        generateTable();
    }

    void generateTable() {
        Object data[][] = new String[alstUpdatedPrograms.size()][5];
        for (int i = 0; i < alstUpdatedPrograms.size(); i++) {
            ProgramUpdateMasterBean objBean = (ProgramUpdateMasterBean) alstUpdatedPrograms.get(i);


            data[i][0] = String.valueOf(objBean.getProgram_ID());
            data[i][1] = String.valueOf(objBean.getUser_ID());
            data[i][2] = objBean.getProgram_Name();
            data[i][3] = objBean.getCreate_Date();
            data[i][4] = objBean.getUpdate_Date();

        }
        String header[] = {"Program ID", "User ID", "Program Name", "Create Date", "Update Date"};
        tblProgramUpdate = new JTable(data, header);
        jScrollPane1.setViewportView(tblProgramUpdate);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProgramUpdate = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ddlUsername = new javax.swing.JComboBox();
        btnList = new javax.swing.JButton();
        btnListAll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        miPrint2 = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblProgramUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Program ID", "User ID", "Program Name", "Create Date", "Update Date"
            }
        ));
        jScrollPane1.setViewportView(tblProgramUpdate);

        jLabel2.setText("Username");

        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        btnListAll.setText("List All");
        btnListAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18));
        jLabel1.setText("Programs Update Report");

        jMenu3.setText("File");

        miPrint2.setText("Print");
        miPrint2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrint2ActionPerformed(evt);
            }
        });
        jMenu3.add(miPrint2);

        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu3.add(miExit);

        jMenuBar3.add(jMenu3);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(ddlUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(btnList, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListAll, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGap(102, 102, 102)))
                .addGap(242, 242, 242))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ddlUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnList)
                    .addComponent(btnListAll))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllActionPerformed
        // TODO add your handling code here:
        alstUpdatedPrograms = objDB.getUpdatedProgramReportList();
        generateTable();
    }//GEN-LAST:event_btnListAllActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        alstUpdatedPrograms = objDB.getUpdatedProgramReportList((String)ddlUsername.getSelectedItem());
        generateTable();
    }//GEN-LAST:event_btnListActionPerformed

    private void miPrint2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrint2ActionPerformed
        // TODO add your handling code here:
        String path = getClass().getResource("../jcodeguard/report/ProgramUpdateReport.jrxml").getPath();
        JasperReportGenerator jrg=new JasperReportGenerator(path);
}//GEN-LAST:event_miPrint2ActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_miExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ProgramUpdateReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnListAll;
    private javax.swing.JComboBox ddlUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miPrint2;
    private javax.swing.JTable tblProgramUpdate;
    // End of variables declaration//GEN-END:variables
}
